cargo-features = ["workspace-inheritance"]

[package]
name = "ecdsa-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true
thiserror.workspace = true

hyperlane-core = { path = "../../../hyperlane-core" }
# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://github.com/solana-foundation/developer-content/blob/main/docs/programs/lang-rust.md#depending-on-rand
getrandom = { workspace = true, features = ["custom"] }

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
