# This is here to satisfy the PR requirements when no rust changes occur.
name: rust

on:
  push:
    branches: [main]
    paths-ignore:
      - 'rust/**'
      - .github/workflows/rust.yml
  pull_request:
    branches: [main]
    paths-ignore:
      - 'rust/**'
      - .github/workflows/rust.yml
  # Support for merge queues
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rs:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test required" '

  lint-rs:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required" '
